### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by starraskind** [starraskind/content-to-code#1]
@wendywarren 

1. main - the primary content of the html
2. h1 - the most important header 
3. time - sets the content as time or date
4. p - a paragraph of text
5. video - embeds a video to the page
6. h2 - the less important header, following h1
7. p - a paragraph of text
8. strong - stronger emphasis of the text with bold
9. data - sets the content as a numerical value
10. time - sets the content as time or date
11. a - a text linked to a path
12. h2 - the less important header, following h1
13. ol - an alphabetically ordered list
14. li - an item inside the list
15. h2 - the less important header, following h1
16. dl - a list with descriptions
17. dt - the title for the listed description
18. dd - the listed description
19. h2 - the less important header, following h1
20. blockquote - a large quote independent from the text
21. p - a paragraph of text
22. footer - the least important information in the text
23. cite - the citation for the quote
24. h2 - the less important header, following h1
25. em -  emphasized text with italics

**Comment by wendywarren** [comment]
Excellent @starraskind!

The only two corrections I have to make are:

#13 - the list is `<ul>` but the list is in alphabetical order so I do see why you decided that but `<ol>` items display with a preceding marker of either a number or letter. Example: 1.,2.,3., or a., b., c., etc...

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol

This was actually answered incorrectly by every student so I know the example given in class was misleading so I'm going to clarify next class. I was even second guessing the correct html element myself but have come to conclusion that it is in fact a `<ul>`.

#25 - `<address>`

Let me know if you have any questions.

Wendy
